name: Publish to PyPI

on:
  release:
    types: [published]


jobs:
  build:
    runs-on: ubuntu-latest
#    environment: development
#    permissions:
#      id-token: write
#      contents: read
    steps:
      - name: Check out repo
        uses: actions/checkout@v4
      - name: Set up python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'
      - name: Display Pythonversion and location
        run: |
          python --version
          which python
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install build    
      - name: Build package
        run: |
          python -m build
      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: simple-http-checker-${{ github.sha }}
          path: dist/    
  publish-tesdtpypi:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Dowload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: simple-http-checker-${{ github.sha }}
          path: dist/
      - name: publish to tesdtpypi
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          repository-url: https://test.pypi.org/legacy
          skip-existing: true
          verbose: true
  

